theme = "docuapi"
themesdir = "../iss/themes/"
languageCode = "en-us"
baseurl = "http://basmyr.net/"
title = "Iss"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "en"

[params]
search = true
  
# Configure the language example tabs.
#[[params.language_tabs]]
#key = "go"
#name = "go"  
[[params.language_tabs]]
key = "javascript"
#key = "sclang"
name = "SuperCollider"
[[params.language_tabs]]
key = "c++"
name = "C++"

#[[params.language_tabs]]
#key = "ruby"
#name = "Ruby"
[[params.language_tabs]]
key = "python"
name = "Python"
[[params.language_tabs]]
key = "sh"
name = "Shell" 



#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "Iss"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='#'>Postlang source at Github</a>",
"Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme by [bep](https://github.com/bep)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true


[languages.el]
languageName = "Ελληνικά"
weight = 1
title = "Ελληνικά"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='#'>Registrer deg for ein utviklarnøkkel</a>",
"Dokumentasjonen er driven av [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme av [bep](https://github.com/bep)"
]

[languages.nn.blackfriday]
# Norwegian uses angled quotes
angledQuotes = true
hrefTargetBlank = true
