---
weight: 10
title: Creative coding
---

* Creative coding

** Introduction

My research imperatives run along the threads of transmediation,
intersemiotic translation, post-disciplinarity and the general concerns of Human Computer Interaction (HCI). 

#+BEGIN_QUOTE
*Key words:* big-data, data, creative-coding, emacs, interaction, machine learning, org-mode, real-time, streaming, web 
#+END_QUOTE

* Mental objectives

The basic elements of programming in general (logic, loops, functions, objects,
classes).

concepts of *object-oriented programming, interactivity, interactive design, connectivity and interconnection*

** Interactive installations

Use of circuits and how to hack them. A great opportunity to learn,
design, recycle old toys and instruments, and transformed them to an alternate instrument.

** Machine learning

- method of data analysis

- data sonification, visualisation

- Programming language

Python




* Methodology and tools

Investigation on different environments and to create interconnection.

creative programming environments:

- Emacs as a basic editor and Git file sharing
(https://github.com/magit/magit), 

- SuperCollider, and
- Python 
- C++ and openFrameworks

for data analysis sonification, visualisation.

** Input devices 

- midi controllers, 
- OSC communication,
- microcontrollers (arduino),
and physical computing,
- sensor usage, 
- multitouch technologies, etc. 

** Organising and sharing

organising and sharing projects using tools such as mass communication techniques Slack-Git.



* SuperCollider

From: [[http://supercollider.github.io][SuperCollider]]

** Basics

SuperCollider is a platform for audio synthesis and algorithmic composition, used by musicians, artists, and researchers working with sound. It is free and open source software available for Windows, macOS, and Linux.

** SuperCollider features three major components:

- *scsynth*, a real-time audio server, forms the core of the platform. It features 400+ unit generators ("UGens") for analysis, synthesis, and processing. Its granularity allows the fluid combination of many known and unknown audio techniques, moving between additive and subtractive synthesis, FM, granular synthesis, FFT, and physical modelling. You can write your own UGens in C++, and users have already contributed several hundred more to the sc3-plugins repository.
- *sclang*, an interpreted programming language. It is focused on sound, but not limited to any specific domain. sclang controls scsynth via Open Sound Control. You can use it for algorithmic composition and sequencing, finding new sound synthesis methods, connecting your app to external hardware including MIDI controllers, network music, writing GUIs and visual displays, or for your daily programming experiments. It has a stock of user-contributed extensions called Quarks.
- *scide* is an editor for sclang with an integrated help system.


  
** Nodes

From: [[https://composerprogrammer.com/teaching/supercollider/sctutorial/6.3%2520Nodes.html][composerprogrammer.com]]

The Server has a graph of all the running Synths, which may be organised into Groups for convenience. You can see Synths and Groups being created just by looking at the Server graphics.

A Node means a Synth or a Group. Whenever you press command+period you reset the graph, cleaning out all the Synths and Groups you added, that is, clearing all Nodes.

The initial state of the Node graph on the Server looks like this (do command+period first to destroy any existing nodes so you have the starting state):

#+BEGIN_SRC js
s.queryAllNodes //run me to see the Nodes on the Server
#+END_SRC

The two default Nodes are convenient Groups for putting your Synths into.

Group(0) is the absolute root of the tree. All new Synths get placed within this Group somewhere (they might be in subGroups but they will be within the RootNode Group at the top of the hierarchy).

#+BEGIN_SRC js
r=RootNode.new; //this gets a reference to Group(0)
#+END_SRC

Group(1) was added as an additional default to receive all created Synths, to avoid cluttering the base of the tree.

#+BEGIN_SRC js
Group.basicNew(s, 1); //this gets a reference to Group(1)
#+END_SRC




** Find recordings folder

#+BEGIN_SRC js
thisProcess.platform.recordingsDir;
#+END_SRC



** Synthesis techniques 


Introduction to sound design (origin, definition, procedures, application fields).

#+BEGIN_QUOTE
SuperCollider example:
Creating a sine wave
#+END_QUOTE


#+BEGIN_SRC js
{SinOsc.ar(440, 0, 0.3)}.play
#+END_SRC

#+BEGIN_QUOTE
Additive synthesis
#+END_QUOTE
#+BEGIN_SRC js
{SinOsc.ar(440, 0, 0.4)+SinOsc.ar(660, 0, 0.3)}.play;
#+END_SRC

#+BEGIN_QUOTE
Subtractive synthesis
#+END_QUOTE

#+BEGIN_SRC js
{LPF.ar(SinOsc.ar(440, 0, 0.4), 6000, 0.3)}.play;
#+END_SRC

#+BEGIN_QUOTE
Granular synthesis
#+END_QUOTE

#+BEGIN_SRC js

SynthDef(\granular, {|out = 0, trig = 1, dur = 0.1, sndbuf, pos = 0.2, 
rate = 1, pan = 0, amp = 0.4|
var env, source;
env = EnvGen.kr(Env.adsr, 1, doneAcion: 2);
source = Out.ar(out, GrainBuf.ar(2, Impulse.kr(trig), dur, sndbuf, rate, pos, 2,
pan, envbuf) * env)
}).add;

#+END_SRC



** Input Devices


Musical gestures can be expressed through a wide range of body
movements. Dozens of input devices have been developed to capture
these gestures. (Roads 1996: 625)

#+BEGIN_QUOTE
Switch
Push buttons
Linear potentiometer or fader
Trackball
Joystick
Game Paddles
etc
#+END_QUOTE
** Instrument design


[[http://bela.io][Bela]]


Capacitive touch sensor-raspberry pi

[[https://learn.adafruit.com/mpr121-capacitive-touch-sensor-on-raspberry-pi-and-beaglebone-black/overview][MPR121]] 




** Mapping the Data from the Input Device

The message coming from digital input devices are streams of binary
numbers. A microprocessor inside the receiving symthesizer must decode
these streams before commanding the synthesis engine  to emit
sound. (Roads 1996: 625)


** Remote Controllers

* Emacs

GNU Emacs
An extensible, customizable, free/libre text editor — and more.
At its core is an interpreter for Emacs Lisp, a dialect of the Lisp programming language with extensions to support text editing.
...[[https://www.gnu.org/software/emacs/][emacs]]

** Install packages

Install org-plus-contrib

#+BEGIN_SRC emacs-lisp

;; add this to your Emacs init file to be able to list the Org mode archives:

(require 'package)

(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)

Then M-x list-packages RET will list both the latest org and
org-plus-contrib packages.

#+END_SRC
** Org-mode

** Create Headers

Start with an *asterisk* to make *Headers* and *two asterisks* for *Subheaders*

Example:

=/* Header/=

=/** Subheader/=

Give a *title* to your page using /hash/ (#) and /plus/ (+) symbols

Example: =/#+Title: Getting started with org-mode/=

#+Title: Getting started with org-mode

*Hide* Table of Contents

Example: =/#+Options: toc:nil/=

#+Options: toc:nil

*Hide* Numbers, table of contents

Example: =/#+Options: num:nil/ toc:nil=

Write =#+= and press =Meta-<tab>= to see the list of variables

Example:

 =#+AUTHOR: Vasilis Agiomyrgianakis=

=#+DATE: 120416=

** Bulleting-Quoting

Use hyphen to make bullets

- bulleted
- list
- items

You can include quotations in Org mode documents like this:

=#+BEGIN_QUOTE=

'QUATATION'

=#+END_QUOTE=

#+BEGIN_QUOTE

A frequent criticism of computer music is the lack of performance, \\
where an artist hides behind their laptop screen, \\
and the audience is unable to see any activity that might ground their experience \\
of the music (Cascone, 2003).


#+END_QUOTE

** Markups

Give *emphasis* to your text.

Write your text *inside* the below symbols:

- 2 asterics for *Bold*,
- 2 slashes for /italics/,
- 2 equals signs for =verbatim=,
- 2 pluses for +strike through text+

*Bold*, /italics/, =verbatim=, +strikethrough+

** Linking 

 Press =C-c C-l= to *link* objects (files)

Example:

/Link: https//:basmyr.net/

Then give a name to the linked text

/Description: Basmyr.net/

 Press =C-c C-o= to *open* the linked plain text with an external program

[[http://basmyr.net][Basmyr.net]]

or a video url

[[https://youtu.be/Wr2aFlWyzvM][Granulator]]

** Tables

Use *pipes - vertical bars* to make tables

Example: Start with pipes and some text:
/| some | | Data |/

then hit return, pipe (vertical bar), hyphen and tab to extend the table verticaly

Press tab and arrows to make arrangements for the table

| Some | Data  |
|------+-------|
|  234 | rocks |
| 1200 | start |

** Images & Graphics
** Images

** Ditaa

*Find the path of ditaa.jar in you computer through a lisp program*

=C-c C-c= to evaluate lisp code inside source block

#+BEGIN_SRC emacs-lisp

(expand-file-name
             "ditaa.jar"
      (file-name-as-directory
            (expand-file-name
                "scripts"
               (file-name-as-directory
                  (expand-file-name
                      "../contrib"
                     (file-name-directory (org-find-library-dir "org")))))))
#+END_SRC


** Export to other formats

Pressing =C-c C-e= popups a buffer to *export* markups to HTML-PDF-etc.

Example: hit =h= and =o= if you want to *export and open as html*.

Export Beamer: =C-c C-e l P=     =(org-beamer-export-to-pdf)=

Export as LaTeX and then process to PDF.

=C-c C-e l O=

Export as LaTeX and then process to PDF, then open the resulting PDF file.

** Source Code

Create code blocks to insert your code.

Press C-c ' *inside the SRC block* to edit the current code block

in the mode of the language you want. For instance:

 =#+BEGIN_SRC emacs-lisp=

write some lisp to make your configurations in org-mode

so as to see bullets (UTF-8 characters) when you editing *Headers* in org-mode instead of asterisks.

Then close the source block with:

=#+END_SRC=

*Result*

#+BEGIN_SRC emacs-lisp

     (require 'org-bullets)
(add-hook 'org-mode-hook
          (lambda () (org-bullets-mode 1)))


#+END_SRC

*You can customise source blocks using =M-x customize-face RET= face RET*

Evaluate source code. Press C-c C-c inside the block and see the results.

 #+BEGIN_Example
 echo "Hello $USER! Today is `date`"
 exit
 #+END_Example

** LaTeX integrator

- Characters: \alpha \rightarrow \beta
- $O(n \log n)$


\begin{align*}
q = 2 * 4 + 1 - 2 &= 7 \\
         q &=7
\end{align*}

** Shortcuts

write down =<s= and press =tab= to open src blocks,

=<q= tab for Quotes,

=<e= tab for Examples

=<c= tab for Center

etc.

to cooment a =lisp= region select a word or a region with C-M-space and then M-; to comment

** TO DO
type TODO to create a todo object
Move the cursor one line after the TODO item and press =C-c C-s= =(org-schedule)=
to schedule with agenda

#+BEGIN_QUOTE
 TODO Call John
SCHEDULED: <2016-11-09 Wed>
#+END_QUOTE

#+BEGIN_QUOTE
 TODO read this and that
SCHEDULED: <2016-11-10 Thu>
#+END_QUOTE

#+BEGIN_QUOTE
 DONE export html minted  (highlight colour - syntax source blocks)
SCHEDULED: <2016-10-12 Wed>
#+END_QUOTE

To open week-agenda window press C-ca
To schedule a TODO item press C-c C-s
Use shift-arrows to change dates


** Github

Introduction to Environments (Github, Bitbucket) for organizing and sharing files-Git.
Set up an account with Slack and Github.

#+BEGIN_QUOTE
Github
#+END_QUOTE

 organize projects and share the
individual processes using tools such as mass communication techniques
Slack-Git.

Git:

- Create a Repository
- Create a Branch
- Make a Commit
- Push and Commit.

[[https://guides.github.com/activities/hello-world/][GitHub Hello world]]


[[https://gist.github.com/davfre/8313299][Github example]]

Https://guides.github.com/activities/hello-world/,
Https://gist.github.com/davfre/8313299

 
** install package magit

Backup rep online in GITLAB, BITBUCKET

create an ssh key to gain access into your repositories in Bitbucker

 Concatanate keys from term

ie. //cat id_rsa.pub | pbcopy


Press =C-x m= to display information about the current Git repository

=P-p= to push rep to bitbucket

=c-c= to commint

=s= to stage rep


 
** Create and concatenate (link) keys on term

create an shh key in GitHub and then open terminal

ie. //cat id_rsa.pub | pbcopy

 
** create .git file inside a folder

Dired to the folder you want to create the .git file and press

=M-x magit-init= and press =y=

 This is a way to say to projectile what is a project and so it will

make your search quicker.

Press =C-cpp= to open projectile


Create a new branch

and then =magit-set-to-upstream= origin


** Pull requests

*issues*

- Git refusing to merge unrelated histories

git cherry-pick -m 1 1234deadbeef1234deadbeef
git rebase --continue

merge

Git failed...

Git refusing to merge unrelated histories

in magit press h to bring the popoup and choose rebase -r and then -p

** Auto-correct

 
** Install Dictionaries -emacs

*Install aspell from brew*

#+BEGIN_Example

$ brew install aspell --with-lang-en --with-lang-el --with-lang-de

#+END_Example

for English, Hellenic and Deutsch languages.

if you have problems installing aspell with the above code

just do only:

#+BEGIN_SRC shell

$ brew install aspell

#+END_SRC

*Install aspell using downloaded packages aspell-0.60.6.1*

go to terminal and type:

#+BEGIN_SRC shell
$ cd ~/aspell path
$ ./configure
$ make
$ make install
#+END_SRC

To install additional dictionary download the language you prefer from  [[ftp://ftp.gnu.org/gnu/aspell/dict/0index.html][GNU_Available Aspell Dictionaries]]

i.e =aspell-el-0.50-3= for Hellenic language (Greek)

and go to terminal and type:

#+BEGIN_SRC shell
$ cd ~/dictionary path
$ ./configure
$ make
$ install
#+END_SRC

*Switch dictionary*

To switch between dictionaries run:

M-x: =ispell-change-dictionary=

and write /greek/ for Hellenic language auto-correct

Press F6 (fn-F6) to switch between dictionaries (british, greek, german)

If you want to use the english dictionary in a particular buffer instead,
put the following on the first line of the buffer:

=-*- ispell-dictionary: "english" -*-=

*Use flyspell instead of ispell*

#+BEGIN_SRC lisp
(setq ispell-list-command "--list")
#+END_SRC
 
** text expansion

install YASnippet using MELPA

put the below into your init.el

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path
             "~/.emacs.d/plugins/yasnippet")
(require 'yasnippet)
(yas-global-mode 1)
#+END_SRC

quit emacs and open again and type

=M-x yas-new-snippet=

- Give a name to your snippet
- give the abrev
- write your text or code you want to be expanted
- save file C-c C-c
- choose a table i.e prog-mode
- give a name to your snippet (I use the abrev key as the name)

try using the abrev key and press tab to expant your text.


** Searching Help


C-h f (or M-x describe-function) will show you the bindings for a command.
You are correct, C-h b (or M-x describe-bindings) will show you all bindings. C-h m (M-x describe-mode) is also handy to list bindings by mode.
You might also try C-h k (M-x describe-key) to show what command is bound to a key. For instance, on my machine save-buffers-kill-emacs isn't bound to anything, but C-h k C-x C-c tells me that C-x C-c is bound to save-buffers-kill-terminal. It will list all bindings for the command at the same time.


helm swoop

help C-h

 
** Export references to pdf with org-mode - bibtex

Use bibtex package for citation.

First put the bellow code in your ./emacs

Below is an example of bibtex style


#+BEGIN_SRC latex
@ARTICLE{2011ApJS..192....9T,
   author = {{Turk}, M.~J. and {Smith}, B.~D. and {Oishi}, J.~S. and {Skory}, S. and
     {Skillman}, S.~W. and {Abel}, T. and {Norman}, M.~L.},
    title = "{yt: A Multi-code Analysis Toolkit for Astrophysical Simulation Data}",
  journal = {The Astrophysical Journal Supplement Series},
archivePrefix = "arXiv",
   eprint = {1011.3514},
 primaryClass = "astro-ph.IM",
 keywords = {cosmology: theory, methods: data analysis, methods: numerical },
     year = 2011,
    month = jan,
   volume = 192,
      eid = {9},
    pages = {9},
      doi = {10.1088/0067-0049/192/1/9},
   adsurl = {http://adsabs.harvard.edu/abs/2011ApJS..192....9T},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

#+END_SRC

#+BEGIN_QUOTE
and this:
#+END_QUOTE


#+BEGIN_SRC latex
@InProceedings{ alejandro_weinstein-proc-scipy-2016,
  author    = { {A}lejandro {W}einstein and {W}ael {E}l-{D}eredy and {S}téren {C}habert and {M}yriam {F}uentes },
  title     = { {F}itting {H}uman {D}ecision {M}aking {M}odels using {P}ython },
  booktitle = { {P}roceedings of the 15th {P}ython in {S}cience {C}onference },
  pages     = { 1 - 6 },
  year      = { 2016 },
  editor    = { {S}ebastian {B}enthall and {S}cott {R}ostrup }
}

#+END_SRC

 then use these latex commands inside your org file

#+BEGIN_Example
#+LaTeX_HEADER: \usepackage[natbib]{biblatex}
#+LATEX_HEADER: \bibliographystyle{plain}
#+LATEX_HEADER: \bibliography{test-bib-refs}
#+END_Example

** Tests

** Test1 slide

   - This is test1 

#+BEGIN_QUOTE
\cite{2011ApJS..192....9T}.
#+END_QUOTE

   - This is test2

#+BEGIN_QUOTE
\cite{alejandro_weinstein-proc-scipy-2016}.
#+END_QUOTE   
 


#+BEGIN_QUOTE
\printbibliography
#+END_QUOTE



** Note

 put =\printbibliography= at the end so as to print the references section last on your text.



* Python 3.5


Introduction to Python (https://www.python.org/doc/).


#+BEGIN_QUOTE
Python
#+END_QUOTE

#+BEGIN_SRC python

# Python 3: Fibonacci series up to n
 def fib(n):
     a, b = 0, 1
     while a < n:
         print(a, end=' ')
         a, b = b, a+b
     print()
 fib(1000)

#+END_SRC



** IPython-notebook

- IPython notebook is used to analyse data and for data visualisation.


** Installation

- install =python 3.5= and anacoda3

call anacoda3 form terminal 

#+BEGIN_SRC shell

➜  ~ source activate anaconda3

#+END_SRC

then call jupyter

#+BEGIN_SRC shell

➜  ~ jupyter notebook

#+END_SRC

Go to emacs and do = M-x ein:notebooklist-login=
Start IPython notebook server.
Hit =M-x ein:notebooklist-open= to open notebook list. This will open notebook
list buffer.
In the notebook list buffer, you can navigate to your folders to [open], or [create], and [delete] notebooks by hitting

- install ipython emacs on melpa 'ein'

copy =ein.el= and =ein.py= to the upload directory

#+BEGIN_QUOTE
open =init.el= and write
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
(require 'ein)
#+END_SRC

#+BEGIN_QUOTE
CERN examples: /particle-physics-playground-playground-52de62d/

#+END_QUOTE

*Sonifying ems (muons) - ipython - SuperCollider in emacs* 

Editor: Emacs Version 24.5 (9.0)

Ipython package **ein** on MELPA

Data sonification experiment on particle-physics-playground.

For more info see here: https://github.com/particle-physics-playground
  
- Sending OSC messages to other application

to send osc messages to other application install *python-osc* library

In this case I use SuperCollider port *57120*



#+BEGIN_SRC python

#VA_exp_280217_001


#Import libraries numpy, matplotlib, pythonosc

In [1]
import numpy as np
import matplotlib.pylab as plt

from IPython import get_ipython
get_ipython().run_line_magic('matplotlib', 'inline')

In [2]
#from __future__ import print_function
#from __future__ import division
import sys

sys.path.append("../particle-physics-playground-Sonification-Example_001/tools/")

#from draw_objects3D import *
import cms_tools as cms



In [3]
infile = open('../particle-physics-playground-Sonification-Example_001/data/small_cms_test_file.dat')

collisions = cms.get_collisions(infile)

number_of_collisions = len(collisions)
print ("# of proton-proton collisions: %d" % (number_of_collisions))


# of proton-proton collisions: 10


In [4]
print (collisions[0])


[[[88.9127, 32.9767, -75.1939, 29.541, -1.0], [79.2211, -58.6558, 49.1723, 13.5915, -1.0], [43.313, -5.9129, 40.0892, 12.0431, -1.0], [274.8094, -21.4194, 27.5639, -272.4152, -1.0], [26.6201, 0.5268, -24.7563, -7.4046, 0.0]], [[15.7375, 1.4793, -15.2566, -3.5645, -1]], [], [[52.364, 17.4983, -45.4233, 19.3009], [10.2904, -1.4633, 10.0887, 1.4035]], [44.9415, 0.422]]


In [5]

print (len(collisions[0]))

5


In [6]
METx = collisions[0][4][0]
METy = collisions[0][4][1]

print ("MET x: %f" % (METx))
print ("MET y: %f" % (METy))

MET x: 44.941500
MET y: 0.422000


In [7]
print ("# of jets:      %d" % (len(collisions[0][0])))
print ("# of muons:     %d" % (len(collisions[0][1])))
print ("# of electrons: %d" % (len(collisions[0][2])))
print ("# of photons:   %d" % (len(collisions[0][3])))

# of jets:      5
# of muons:     1
# of electrons: 0
# of photons:   2


In [8]
jets,muons,electrons,photons,met = collisions[0]


In [9]
E,px,py,pz,btag = jets[0]
print ("E:     %8.4f" % (E))
print ("px:    %8.4f" % (px))
print ("py:    %8.4f" % (py))
print ("pz:    %8.4f" % (pz))
print ("btag:  %8.4f" % (btag))

E:      88.9127
px:     32.9767
py:    -75.1939
pz:     29.5410
btag:   -1.0000


In [10]
E,px,py,pz,q = muons[0]
print ("E:  %8.4f" % (E))
print ("px: %8.4f" % (px))
print ("py: %8.4f" % (py))
print ("pz: %8.4f" % (pz))
print ("q:  %8.4f" % (q))

E:   15.7375
px:   1.4793
py: -15.2566
pz:  -3.5645
q:   -1.0000


In [11]
E,px,py,pz = photons[0]
print ("E:  %8.4f" % (E))
print ("px: %8.4f" % (px))
print ("py: %8.4f" % (py))
print ("pz: %8.4f" % (pz))

E:   52.3640
px:  17.4983
py: -45.4233
pz:  19.3009


In [0]
      # Plot the quantities
plt.figure(figsize=(16,4))

plt.subplot(1,3,1)
plt.hist(njets,bins=5,range=(0,5))
plt.xlabel(r'# of jets')
plt.ylabel('# entries')

plt.subplot(1,3,2)
plt.hist(jets_E,bins=25,range=(0,400))
plt.xlabel(r'Jet energy [GeV]')
plt.ylabel('# entries')

plt.subplot(1,3,3)
plt.hist(muons_E,bins=25,range=(0,400))
plt.xlabel(r'Muon energy [GeV]')
plt.ylabel('# entries')

h1:
Watch an example

In [0]
from IPython.display import YouTubeVideo
YouTubeVideo('UfimSbOr9to')

In [13]
infile = open('../particle-physics-playground-Sonification-Example_001/data/mc_dy_1000collisions.dat')


collisions = cms.get_collisions(infile)

# We will use these to store the quantities that we will be plotting later.
njets = []
jets_E = []
muons_E = []
photons_E = []

for collision in collisions:
    
    jets,muons,electrons,photons,met = collision
    
    njets.append(len(jets))
    
    for jet in jets:
        E,px,py,pz,btag = jet
        jets_E.append(px)

    for muon in muons:
        E,px,py,pz,q = muon
        muons_E.append(E)
        
    for photon in photons:
        E,px,py,pz = photon
        photons_E.append(E)

  

In [18]
import time

infile = open('../particle-physics-playground-Sonification-Example_001/data/mc_dy_1000collisions.dat')


collisions = cms.get_collisions(infile)

# We will use these to store the quantities that we will be plotting later.
njets = []
jets_E = []
muons_E = []
photons_E = []

for collision in collisions:
    
    jets,muons,electrons,photons,met = collision
    
    njets.append(len(jets))
    
    for jet in jets:
        E,px,py,pz,btag = jet
        jets_E.append(E )

    for muon in muons:
        E,px,py,pz,q = muon
        muons_E.append(E)
        
    for photon in photons:
        E,px,py,pz = photon
        photons_E.append(E)

        
             # Set up OSC here
  
from pythonosc import osc_message_builder
from pythonosc import udp_client

# The port for SuperCollider is '57120'

client = udp_client.SimpleUDPClient("127.0.0.1", 57120)


#client.send_message("/print", muons_E)

# now we can print them out too

for i in muons_E:
      print ("muon was: %d" % i)
      client.send_message("/print", i)
      time.sleep(0.015)

for i in jets_E:
      print ("jet was: %d" % i)
      client.send_message("/print", i)
      time.sleep(0.015)

for i in photons_E:
      print ("photon was: %d" % i)
      client.send_message("/print", i)
      time.sleep(0.015)
# # Plot the quantities


#+END_SRC

* Micro-computing


** Physical computing

Introduction to physical computing - microcontrollers. Programming
Interactivity (Noble 2012): Chapter 4: Arduino.

Introduction to Raspberry Pi
(https://www.raspberrypi.org/learning/hardware-guide/).

** Interactive Performance.

  set of practices that give performers (usually dancers or musicians) control of the media in real time?

 wireless sensors found both in the body of an performer and in the
 theater.

** Sensors

Use of sensors: touch, movement, elasticity, camera.

*Programming Interactivity* 

experimenting with various sensors.

experimenting with Arduino and node.js

Arduino basic examples:
(https://www.arduino.cc/en/Tutorial/BuiltInExamples).

Using Python-for OSC communication libraries 

(https://pypi.python.org/pypi/python-osc) - with SuperCollider.

** Raspberry Pi

 
Install Linux Raspbian Jessie Lite OS Image on the SD card

Download Raspbian here:
[[https://www.raspberrypi.org/downloads/raspbian/][raspbian]]

Follow the instructions here:
[[https://www.raspberrypi.org/documentation/installation/installing-images/README.md][installation-guide]]



** Hardware set up

[[http://supercollider.github.io/development/building-raspberrypi][Building from Source on Raspberry]]

#+BEGIN_QUOTE
- connect an ethernet cable from the network router to the rpi
- insert the sd card and usb soundcard
- last connect usb power from a 5V@1A power supply

#+END_QUOTE

** Login & preparations

#+BEGIN_SRC shell
$ ssh pi@raspberrypi.local #from your laptop, default password is raspberry
$ sudo raspi-config #change password, expand file system, reboot and log in again with ssh
#+END_SRC

#+BEGIN_QUOTE
update the system, install required libraries & compilers
#+END_QUOTE

#+BEGIN_SRC shell
$sudo apt-get update

$sudo apt-get upgrade

$sudo apt-get install alsa-base libicu-dev libasound2-dev libsamplerate0-dev libsndfile1-dev libreadline-dev libxt-dev libudev-dev libavahi-client-dev libfftw3-dev cmake git gcc-4.8 g++-4.8

#+END_SRC

#+BEGIN_QUOTE
compile & install jackd (no d-bus)
#+END_QUOTE

#+BEGIN_SRC shell
$git clone git://github.com/jackaudio/jack2 --depth 1
$cd jack2
$./waf configure --alsa #note: here we use the default gcc-4.9
$./waf build
$sudo ./waf install
$sudo ldconfig
$cd ..
$rm -rf jack2
$sudo nano /etc/security/limits.conf #and add the following two lines at the end
    * @audio - memlock 256000
    * @audio - rtprio 75
 exit #and log in again to make the limits.conf settings work

#+END_SRC

#+BEGIN_QUOTE
compile & install sc master
#+END_QUOTE

#+BEGIN_SRC shell
$git clone --recursive git://github.com/supercollider/supercollider
#optionally add –depth 1 here if you only need master
$cd supercollider
$git submodule init && git submodule update
$mkdir build && cd build
$export CC=/usr/bin/gcc-4.8 #here temporarily use the older gcc-4.8
$export CXX=/usr/bin/g++-4.8
$cmake -L -DCMAKE_BUILD_TYPE="Release" -DBUILD_TESTING=OFF -DSSE=OFF -DSSE2=OFF
-DSUPERNOVA=OFF -DNOVA_SIMD=ON -DNATIVE=OFF -DSC_ED=OFF
-DSC_WII=OFF -DSC_IDE=OFF -DSC_QT=OFF -DSC_EL=OFF -DSC_VIM=OFF
-DCMAKE_C_FLAGS="-mtune=cortex-a7 -mfloat-abi=hard -mfpu=neon
-funsafe-math-optimizations" 
-DCMAKE_CXX_FLAGS="-mtune=cortex-a7 -mfloat-abi=hard -mfpu=neon
-funsafe-math-optimizations" ..
$make -j 4 #leave out flag j4 on single core rpi models
$sudo make install
$sudo ldconfig
$cd ../..
$rm -rf supercollider
$sudo mv /usr/local/share/SuperCollider/SCClassLibrary/Common/GUI
/usr/local/share/SuperCollider/SCClassLibrary/scide_scqt/GUI
$sudo mv /usr/local/share/SuperCollider/SCClassLibrary/JITLib/GUI
/usr/local/share/SuperCollider/SCClassLibrary/scide_scqt/JITLibGUI
#+END_SRC

#+BEGIN_QUOTE
start jack & sclang & test
#+END_QUOTE

#+BEGIN_SRC shell
$jackd -P75 -dalsa -dhw:1 -p1024 -n3 -s -r44100 & 
#edit -dhw:1 to match your soundcard. usually it is 1 for usb, or,jackd -P75-dalsa -dhw:UA25EX -p1024
-n3 -s -r44100 &
$sclang #should start sc and compile the class library with 
only 3 harmless class overwrites warnings
    $s.boot #should boot the server
    $ a= {SinOsc.ar([400, 404])}.play #should play sound in both channels
    $ a.free
     {1000000.do{2.5.sqrt}}.bench #benchmark: ~0.89 for rpi2, ~3.1 for rpi1
    $ a= {Mix(50.collect{RLPF.ar(SinOsc.ar)});DC.ar(0)}.play#benchmark
    $ s.dump #avgCPU should show ~19% for rpi2 and ~73% for rpi1
    $ a.free
    $ 0.exit #quit sclang
$ pkill jackd #quit jackd
#+END_SRC

* Suggested Bibliography

** Books

